### ISSUE TITLE
pending questions

### ISSUE THREAD

**Issue by azziliz** [azziliz/MurmuresJS#100]

**Comment by azziliz** [comment]
1. Which layer should have physical properties? Currently the ground/wall layer and the prop layer both have physics that can block movement/vision. Is it really needed? It slows the FOV algorithm down for little benefits. Should we drop the physics on prop layer?

**Comment by azziliz** [comment]
2. Which layer may have a special behavior? Currently the prop layer is the only one that can have it. Do we need it on another layer?

**Comment by thyshimrod** [comment]
2 - Special behavior only on prop layer, from my mind

1 - I think, we can put only on ground layer. If an object must block, or something else, the good pratice, is to put a blocking ground under the item.
I wonder about moveable blocking items (a rock for example in a puzzle...)... but it is another topic.
